
FROM python:3.11



RUN git clone https://github.com/SampleEnvironment/frappy.git

WORKDIR /frappy

RUN  git checkout ROCK-IT-sim



ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
RUN pip install -r requirements.txt
RUN pip install numpy

CMD ["python3", "bin/frappy-server","-c","cfg/sim_hzb_gas_analysis_cfg.py", "gas_analysis"]
